service: custom-serverless-plugins

plugins:
  - ./custom-serverless-plugin

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: eu-west-1

custom:
  defaultRegion: eu-west-1

functions:
  hello:
    handler: handler.hello
